packages:
  - packages/*
saveExact: true

# CATALOG
catalog:
  config: 4.1.1
  rxjs: 7.8.2
  tslib: 2.8.1
  ts-morph: 27.0.0
  winston: 3.17.0
  yaml: 2.8.1

catalogs:
  # DEPENDENCY
  eslint:
    '@stylistic/eslint-plugin': 5.4.0
    eslint-import-resolver-typescript: 4.4.4
    eslint-plugin-import-x: 4.16.1
    typescript-eslint: 8.44.1
  nx:
    '@nx/devkit': 21.5.3
    '@nx/jest': 21.5.3
    '@nx/js': 21.5.3
    '@nx/workspace': 21.5.3
  # DEPENDENCY PEER
  nestjs:
    '@nestjs/common': '>= 11.0.0'
    '@nestjs/core': '>= 11.0.0'
    '@nestjs/microservices': '>= 11.0.0'
    '@nestjs/swagger': '>= 11.0.0'
  peer:
    '@sentry/node': '>= 10.0.0'
    eslint: '>= 9.0.0'
    enquirer: '>= 2.3.0'
    nestjs-cls: '>= 5.0.0'
    nx: '>= 21.0.0'
    reflect-metadata: '>= 0.1.0'
    ts-node: '>= 10.0.0'
    ts-node-dev: '>= 2.0.0'
    typeorm: '>= 0.3.21'
    typescript: '>= 3.9.0'
