export const KEYCLOAK_CONNECT_OPTIONS = Symbol('KEYCLOAK_CONNECT_OPTIONS')
export const KEYCLOAK_CONNECT_INSTANCE = Symbol('KEYCLOAK_CONNECT_INSTANCE')

export const KEYCLOAK_CONNECT_METADATA_UNPROTECTED = Symbol('KEYCLOAK_CONNECT_METADATA_UNPROTECTED')
export const KEYCLOAK_CONNECT_METADATA_PROTECTED = Symbol('KEYCLOAK_CONNECT_METADATA_PROTECTED')
export const KEYCLOAK_CONNECT_METADATA_GROUPS = Symbol('KEYCLOAK_CONNECT_METADATA_GROUPS')
export const KEYCLOAK_CONNECT_METADATA_ROLES = Symbol('KEYCLOAK_CONNECT_METADATA_ROLES')
export const KEYCLOAK_CONNECT_METADATA_SCOPES = Symbol('KEYCLOAK_CONNECT_METADATA_SCOPES')
export const KEYCLOAK_CONNECT_METADATA_USER = Symbol('KEYCLOAK_CONNECT_METADATA_USER')
